name: build-pyorbit
on: push
jobs:
 centos-stream:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream
    steps:
         - uses: actions/checkout@v4
           with:
            fetch-depth: '0'

         - name: Install packages
           run: |
             dnf group install -y "Development Tools"
             dnf install -y python3-devel openmpi-devel fftw3-devel

         - name: Make
           run: |
             .github/workflows/build.sh
         - name: Test
           run: |
             .github/workflows/run-tests.sh