name: build-pyorbit
on: push
jobs:
 centos-stream:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9
    steps:
         - name: Install packages
           run: |
             dnf group install -y "Development Tools"
             dnf install -y python3-devel openmpi-devel fftw3-devel

         - uses: actions/checkout@v2
           with:
            fetch-depth: 0

         - name: Build
           run: |
             .github/workflows/build.sh

         - name: Test
           run: |
             .github/workflows/run-tests.sh